### ISSUE TITLE
Visual Studio Code is unable to watch for file changes in this large workspace

### ISSUE THREAD

**Issue by emilmuller** [flathub/com.visualstudio.code#134] opened 2020-02-02 14:36 UTC
`**/node_modules/**` has been added to watcherExclude in settings. So it's basically just 2 files it has to watch. Nevertheless, I am getting this:

![image](https://user-images.githubusercontent.com/2487546/73609837-a8c22a80-45d1-11ea-8d2c-997f6cc35634.png)

Kind regards, Emil

**Comment by jurf** [comment] 2020-03-19 17:31
Have you tried the [instructions](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc) linked in #29?

**Comment by jurf** [comment] 2020-03-19 17:32
Even so, this is a duplicate of #93.

**Comment by eszlari** [comment] 2020-03-20 05:00
Closed because of duplicate.

**Closed by eszlari** 2020-03-20 05:00 UTC
