### ISSUE TITLE
Visual studio not opening after update to 1.58

### ISSUE THREAD

**Issue by FloUhl** [flathub/com.visualstudio.code#232] opened 2021-07-09 09:56 UTC
I updated the flatpak today to 1.58 and since then I cannot open VSCode as it crashes on opening.

Running on Fedora 34, as far as I know all updates, no beta-versions of software installed.

Here is the output of `journalctl -f` for an attempt to open the program.

```
Jul 09 11:45:00 f-desk systemd[2666]: Started Application launched by gnome-shell.
Jul 09 11:45:00 f-desk systemd[2666]: app-glib-com.visualstudio.code-9428.scope: Deactivated successfully.
Jul 09 11:45:00 f-desk systemd[2666]: Started app-flatpak-com.visualstudio.code-9428.scope.
Jul 09 11:45:00 f-desk systemd[2666]: app-gnome-com.visualstudio.code-9428.scope: Deactivated successfully.
Jul 09 11:45:00 f-desk audit[9460]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=9460 comm="code" exe="/app/extra/vscode/code" sig=5 res=1
Jul 09 11:45:00 f-desk kernel: traps: code[9460] trap int3 ip:55e12afa34f8 sp:7ffe14d9cf90 error:0 in code[55e12ad72000+5dfb000]
Jul 09 11:45:00 f-desk audit: BPF prog-id=94 op=LOAD
Jul 09 11:45:00 f-desk audit: BPF prog-id=95 op=LOAD
Jul 09 11:45:00 f-desk audit: BPF prog-id=96 op=LOAD
Jul 09 11:45:00 f-desk systemd[1]: Started Process Core Dump (PID 9463/UID 0).
Jul 09 11:45:00 f-desk audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@7-9463-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 09 11:45:01 f-desk systemd-coredump[9464]: [🡕] Process 9460 (code) of user 1000 dumped core.
                                               
                                               Stack trace of thread 20:
                                               #0  0x000055e12afa34f8 n/a (/app/extra/vscode/code + 0x19f24f8)
                                               #1  0x000055e12cd55654 n/a (/app/extra/vscode/code + 0x37a4654)
                                               #2  0x000055e12bc91d1c n/a (/app/extra/vscode/code + 0x26e0d1c)
                                               #3  0x000055e12c196def n/a (/app/extra/vscode/code + 0x2be5def)
                                               #4  0x000055e12c115f78 n/a (/app/extra/vscode/code + 0x2b64f78)
                                               #5  0x000055e12c115b71 n/a (/app/extra/vscode/code + 0x2b64b71)
                                               #6  0x000055e12f4e3328 n/a (/app/extra/vscode/code + 0x5f32328)
                                               #7  0x000055e12f4e1999 n/a (/app/extra/vscode/code + 0x5f30999)
                                               #8  0x000055e12f4e1ae2 n/a (/app/extra/vscode/code + 0x5f30ae2)
                                               #9  0x000055e12f08b0bf n/a (/app/extra/vscode/code + 0x5ada0bf)
                                               #10 0x00007f487514d062 n/a (/usr/lib/x86_64-linux-gnu/libc-2.31.so + 0x24062)
Jul 09 11:45:01 f-desk systemd[1]: systemd-coredump@7-9463-0.service: Deactivated successfully.
Jul 09 11:45:01 f-desk audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@7-9463-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 09 11:45:01 f-desk audit: BPF prog-id=96 op=UNLOAD
Jul 09 11:45:01 f-desk audit: BPF prog-id=95 op=UNLOAD
Jul 09 11:45:01 f-desk audit: BPF prog-id=94 op=UNLOAD
Jul 09 11:45:01 f-desk dleyna-renderer-service[9391]: dLeyna: Exit
Jul 09 11:45:01 f-desk dleyna-renderer-service[9420]: dLeyna: Exit
Jul 09 11:45:01 f-desk systemd[2666]: dbus-:1.2-com.intel.dleyna\x2drenderer@15.service: Deactivated successfully.
Jul 09 11:45:01 f-desk systemd[2666]: dbus-:1.2-com.intel.dleyna\x2drenderer@16.service: Deactivated successfully.
Jul 09 11:45:01 f-desk abrt-server[9479]: Unsupported container technology
Jul 09 11:45:01 f-desk abrt-server[9479]: Lock file '.lock' was locked by process 9482, but it crashed?
Jul 09 11:45:01 f-desk systemd[2666]: app-flatpak-com.visualstudio.code-9428.scope: Deactivated successfully.
Jul 09 11:45:03 f-desk abrt-server[9479]: Error: No segments found in coredump './coredump'
Jul 09 11:45:03 f-desk abrt-server[9479]: Can't open file 'core_backtrace' for reading: No such file or directory
Jul 09 11:45:03 f-desk abrt-server[9479]: Deleting problem directory ccpp-2021-07-09-11:45:01.314981-9460 (dup of ccpp-2021-07-09-11:16:41.206082-10307)
Jul 09 11:45:03 f-desk abrt-notification[9548]: [🡕] Process 10307 (code) crashed in ??()
```

If there is any more information required please let me know.

**Comment by carlocastoldi** [comment] 2021-07-09 11:38
I have the same problem.
I have seen 677525d16dc5f46108c8fbf990bedd33b3ba53db should fix it (?)

For the time being I solved  with a downgrade:
```
# flatpak update --commit=9fd33f863da93723ed2c94d63e55bfd2af599d67e57d68c4fc4bb9022e432b0a com.visualstudio.code
```

**Comment by noverby** [comment] 2021-07-13 04:30
Running with `--no-sandbox` allows VS Code to run.
Maybe we need to change the permission of `chrome-sandbox`: https://github.com/electron/electron/issues/17972

**Comment by gasinvein** [comment] 2021-07-15 18:24
Duplicate of #223

**Closed** 2021-07-19 04:56 UTC
