### ISSUE TITLE
Enabling extensions using `FLATPAK_ENABLE_SDK_EXT` broken

### ISSUE THREAD

**Issue by mkfrey** [flathub/com.visualstudio.code#259] opened 2021-10-06 14:08 UTC
Enabling extensions using `FLATPAK_ENABLE_SDK_EXT` does no longer work. When starting vscode from commandline, `flatpak-vscode: Enabling SDK extension "<extension>"` is printed, but the relevant binary paths are not added to $PATH.

**Comment by mkfrey** [comment] 2021-10-06 14:45
This line seems to be the culprit: https://github.com/flathub/com.visualstudio.code/blob/7aeabcc81ccccc6b6266c42b4806853ec637686e/code.sh#L63
Setting `ELECTRON_RUN_AS_NODE=1` seems to mess with the environment somehow.

**Comment by bytzo** [comment] 2021-10-08 02:09
It looks like the addition of zypak in 3b6325a13fd1b5e3a33b64587700e7c4437c75c1 is the cause of this issue.

https://github.com/flathub/com.visualstudio.code/blob/3b6325a13fd1b5e3a33b64587700e7c4437c75c1/code.sh#L64

When using zypak, the `$PATH` environment variable from the wrapper script is not passed to the electron binary, preventing most tools from finding the currently enabled SDKs. Since I'm not very familiar with Flatpaks or shell scripting, I'm not sure what the solution to this would be. However, as a quick workaround, you should be able to manually point your tools to the SDKs located in `/usr/lib/sdk` (for example, `"java.home": "/usr/lib/sdk/openjdk"` for the OpenJDK SDK extension).

**Comment by bytzo** [comment] 2021-10-08 23:29
Setting the `ELECTRON_RUN_AS_NODE` variable allows for CLI arguments to be passed to the application. If you try removing the variable and running `flatpak run com.visualstudio.code --help`, the application will launch as normal instead of showing the help menu. However, you are correct that unsetting it fixes the SDK issue (I didn't notice this before, probably forgot to set `FLATPAK_ENABLE_SDK_EXT` when testing :P)

`ELECTRON_RUN_AS_NODE` was not set before since the built-in wrapper script (`/app/extra/vscode/bin/code`) already does it. However, since zypak must call the Electron binary directly (`/app/extra/vscode/code`), the wrapper script was bypassed, meaning the variable had to be set manually.

**Comment by mkfrey** [comment] 2021-10-30 15:55
I don't know if this would change much, since the built-in wrapper does not look like it contains any meaningful difference to the custom one.

The PATH variable somehow gets eaten somwhere behind the zypak wrapper. But only if `ELECTRON_RUN_AS_NODE` is active.

**Comment by vteivans** [comment] 2022-02-01 14:35
I'm having the same issue, but for me it's not just `$PATH` that isn't set. The `npm_config_nodedir` is not set either. And the only thing that enables those two lines, is running `source enable.sh` later.

**Comment by bytzo** [comment] 2022-05-31 05:10
This should have been fixed by #300. I am unable to reproduce this issue with the latest Flatpak version of VSCode and the `org.freedesktop.Sdk.Extension.openjdk` SDK extension using the `FLATPAK_ENABLE_SDK_EXT=*` environment variable. Is this true for everyone else?

**Comment by YaLTeR** [comment] 2022-05-31 05:24
The texlive extension loaded fine for me some weeks ago.

**Closed** 2022-05-31 07:40 UTC
