### ISSUE TITLE
Update Store icon to new version

### ISSUE THREAD

**Issue by superusercode** [flathub/com.visualstudio.code#18] opened 2018-02-10 00:20 UTC
The GNOME Software app still shows the orange logo. 
![screenshot from 2018-02-09 19-17-55](https://user-images.githubusercontent.com/23001825/36055958-45d1cba2-0dce-11e8-9d73-44e34cb37597.png)

**Comment by nedrichards** [comment] 2018-02-10 08:14
Duplicate of #13 this basically needs us to remove the remote icon from the appdata since we ship icons now

**Closed by nedrichards** 2018-02-10 08:14 UTC
