### ISSUE TITLE
"bash: cannot set terminal process group (-1): Inappropriate ioctl for device" when open Visual Studio Code integrated terminal

### ISSUE THREAD

**Issue by ghost** [flathub/com.visualstudio.code#315] opened 2022-05-16 16:53 UTC
# Linux distribution and kernel version
Arch Linux x86_64 
5.17.7-arch1-1

# Flatpak version
Flatpak 1.12.7

# Description of the problem
When I configure the integrated terminal according to the flatpak_warning.txt in the config file located in `~/.var/app/com.visualstudio.code/config/Code/User/settings.json`
```
{
  "terminal.integrated.defaultProfile.linux": "bash",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "path": "/usr/bin/flatpak-spawn",
      "args": ["--host", "--env=TERM=xterm-256color", "bash"]
    }
  }
}
```
I get the following message every time I open the integrated terminal
```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```
![image](https://user-images.githubusercontent.com/105663878/168643837-1bfe9670-fb64-4af0-88cf-d4f3aaec33cf.png)

**Comment by nikodunk** [comment] 2022-05-17 00:40
I get this too but the terminal works just fine. Does your terminal work?

**Comment by tinywrkb** [comment] 2022-07-12 11:21
You need a new pty to avoid the controling tty issue. This can be achieved with screen.

```
"terminal.integrated.profiles.linux": {
  "Host: Bash (new pty)": {
    "path": "/usr/bin/flatpak-spawn",
    "args": ["--env=TERM=vscode", "--host", "script", "--quiet", "/dev/null"]
  },
  "Host: ZSH (new pty)": {
    "path": "/usr/bin/flatpak-spawn",
    "args": ["--env=TERM=vscode", "--env=SHELL=zsh", "--host", "script", "--quiet", "/dev/null"]
  }
}
```

**Comment by tinywrkb** [comment] 2022-07-12 12:48
[host-spawn](https://github.com/1player/host-spawn) is even better.

**Comment by ferrybig** [comment] 2022-11-02 08:32
> You need a new pty to avoid the controlling terminal issue. This can be achieved with script.
> 
> ```
> "terminal.integrated.profiles.linux": {
>   "Host: Bash (new pty)": {
>     "path": "/usr/bin/flatpak-spawn",
>     "args": ["--env=TERM=vscode", "--host", "script", "--quiet", "/dev/null"]
>   },
>   "Host: ZSH (new pty)": {
>     "path": "/usr/bin/flatpak-spawn",
>     "args": ["--env=TERM=vscode", "--env=SHELL=zsh", "--host", "script", "--quiet", "/dev/null"]
>   }
> }
> ```

For some reason, your solution makes the /usr/bin directory different in the spawned shell, compared to the hosts /usr/bin directory, so not every command works

**Comment by fiantyogalihp** [comment] 2022-12-13 05:48
> You need a new pty to avoid the controlling terminal issue. This can be achieved with script.
> 
> ```
> "terminal.integrated.profiles.linux": {
>   "Host: Bash (new pty)": {
>     "path": "/usr/bin/flatpak-spawn",
>     "args": ["--env=TERM=vscode", "--host", "script", "--quiet", "/dev/null"]
>   },
>   "Host: ZSH (new pty)": {
>     "path": "/usr/bin/flatpak-spawn",
>     "args": ["--env=TERM=vscode", "--env=SHELL=zsh", "--host", "script", "--quiet", "/dev/null"]
>   }
> }
> ```

thanks, my issues is fixed by this :3

**Comment by fiantyogalihp** [comment] 2022-12-13 06:08
> You need a new pty to avoid the controlling terminal issue. This can be achieved with script.
> 
> ```
> "terminal.integrated.profiles.linux": {
>   "Host: Bash (new pty)": {
>     "path": "/usr/bin/flatpak-spawn",
>     "args": ["--env=TERM=vscode", "--host", "script", "--quiet", "/dev/null"]
>   },
>   "Host: ZSH (new pty)": {
>     "path": "/usr/bin/flatpak-spawn",
>     "args": ["--env=TERM=vscode", "--env=SHELL=zsh", "--host", "script", "--quiet", "/dev/null"]
>   }
> }
> ```

the issue is fixed, but can't run some command properly

**Comment by kramfs** [comment] 2022-12-19 11:11
> [host-spawn](https://github.com/1player/host-spawn) is even better.

I concur, [host-spawn](https://github.com/1player/host-spawn) is a better solution. Here's a simple config:
````
    "terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
        "bash": {
          "path": "/var/home/kramfs/.local/bin/host-spawn",
          "icon": "terminal"
        }
    }
````

**Closed** 2023-08-22 17:43 UTC
