### ISSUE TITLE
`[xxx preload-host-spawn-strategy] Warning: waitpid override ignores groups` in the integrated terminal after first start.

### ISSUE THREAD

**Issue by jorchube** [flathub/com.visualstudio.code#370] opened 2022-12-29 12:28 UTC
Hi, 

The Integrated Terminal is showing these `[xxx preload-host-spawn-strategy] Warning: waitpid override ignores groups` warning messages for each and every command executed. 

This happens in a fresh (no configuration, sync, extensions installed or defaults modification of any sort) application, except for the first start ever, after which it happens always.

Attached there is a screencast showing a first start of the application in which the issue does not happen. After closing and reopening again, the warning messages start appearing.

[Screencast from 2022-12-29 12-52-28.webm](https://user-images.githubusercontent.com/1174736/209948303-28c4a942-2869-42dc-bf37-51e2c131b0ee.webm)

This happens both in the default `sh` terminal profiles as well as in the `bash` ones.
These warning messages start flooding the terminal output as they also appear for any subshell spawned as part of an executed command and if the prompt executes anything, so even just pressing enter can lead to a unbearable flood of warning messages as the prompt gets resolved.

Tracking down previous commits, commit `e03d4ed40326424ecd9f55e3e69afa9e6292a149c718d5da2ee35e7c5fafe38c` is the first one exhibiting this issue, and downgrading to the previous one `a3c1c20103d56d180dd30c5bdf25763520dbe0987e2ebadd96922ed109d66626` mitigates it.

```
    Commit: e03d4ed40326424ecd9f55e3e69afa9e6292a149c718d5da2ee35e7c5fafe38c
   Subject: Update 2 modules (4de6104a)
      Date: 2022-12-08 09:39:48 +0000

    Commit: a3c1c20103d56d180dd30c5bdf25763520dbe0987e2ebadd96922ed109d66626
   Subject: Update 2 modules (35102f6c)
      Date: 2022-11-09 20:14:02 +0000

```

On Fedora Silverblue 37,  Wayland, GNOME.

I was not able to reproduce this on a non-flatpak installation.

Please let me know if there is any other information that I can provide.

**Comment by susantpatel** [comment] 2023-01-08 17:11
Same thing happening for me after a fresh installation of linux mint. I have installed VS code form software Manager

**Comment by susantpatel** [comment] 2023-01-08 17:23
I installed it form official vs code website and the issue is gone

**Comment by IkenoMike** [comment] 2023-01-10 15:38
Same issue is happening to me. I will trying installing from the official vs code site and see if that resolves it for me.

**Comment by safejace** [comment] 2023-01-23 23:19
+1 happening with the flatpak

**Comment by cankutayeser** [comment] 2023-01-28 13:33
+1 flatpak

**Comment by Toso42** [comment] 2023-02-14 10:58
+1 flatpak

**Comment by fadykuzman** [comment] 2023-04-22 17:39
+1 IntellJ Idea with flatpak

**Comment by an0pheles** [comment] 2023-04-22 21:17
+1 IntelliJ Community with flatpak on Mint Linux

**Comment by pliuchkin** [comment] 2023-04-23 13:02
+1 Intellij Community with flatpak on OpenSUSE Tumbleweed.

**Comment by Cpyte-Engine-Developer** [comment] 2023-05-08 08:41
+1 flatpak, PyCharm

**Comment by iihmsunn** [comment] 2023-05-08 20:18
a workaround for vscode that seems to be working for me is to add these to settings.json

```
"terminal.integrated.defaultProfile.linux": "bash",
"terminal.integrated.profiles.linux": {
    "bash": {
        "path": "/usr/bin/flatpak-spawn",
        "args": [
            "--env=TERM=xterm-256color",
            "bash",
            //next two lines are only required if you use external sdks, edit to use yours
            "-c",
            "export PATH=$PATH:/usr/lib/sdk/dotnet7/bin:/usr/lib/sdk/node18/bin; bash"
        ]
    }
}

```

**Comment by opravil-jan** [comment] 2023-05-10 12:43
+1 flatpak

**Comment by bruno-henr** [comment] 2023-05-12 20:04
really occurred in vscode flatpak, i just download official version and solved

**Comment by bruno-henr** [comment] 2023-05-12 20:06
[Debian and Ubuntu based distributions](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions)
The easiest way to install Visual Studio Code for Debian/Ubuntu based distributions is to download and install the [.deb package (64-bit)](https://go.microsoft.com/fwlink/?LinkID=760868), either through the graphical software center if it's available, or through the command line with:

sudo apt install ./<file>.deb

**Comment by jcleng** [comment] 2023-05-16 15:02
> +1 IntellJ Idea with flatpak on NixOs 22.11



the same

**Comment by youpie** [comment] 2023-05-25 08:21
+1 flatpak on fedora 38

**Comment by DKraeff** [comment] 2023-05-25 16:46
+1 on Mint

I downloaded it from the Software Manager and it worked just fine but, at one point, it started giving me the same warning.

**Comment by abhigit23** [comment] 2023-05-25 17:09
same issue here too on fedora silverblue 38

**Comment by bantryblues** [comment] 2023-05-26 17:23
Happens to me too on fedora silverblue 38 with flatpak vscode and using toolbox container

[701 preload-host-spawn-strategy] Warning: waitpid override ignores groups
appears 3 times before and after a command is executed

**Comment by ranisalt** [comment] 2023-05-30 21:52
> **Edited:** Uncheck this setting solved the issue for me!!! ![image](https://user-images.githubusercontent.com/88484339/241705894-42e8d748-3d15-4285-8b12-8fc8d51e30e2.png)

This is the answer. The flatpak should see if it's possible to override this setting, as it comes enabled by default. Principle of most astonishment, I guess...

**Comment by AlexanderTonn** [comment] 2023-06-01 10:52
+1 Linux Mint 21.1 Vera, but the issue is gone after the tip with the "deactivating Use Sandbox" Workaround (see below)

**Comment by Calastrophe** [comment] 2023-06-02 02:39
> **Edited:** Uncheck this setting solved the issue for me!!! ![image](https://user-images.githubusercontent.com/88484339/241705894-42e8d748-3d15-4285-8b12-8fc8d51e30e2.png)

This fixed the issue for me. Pop OS 22.04 LTS.

**Comment by dimib-tech** [comment] 2023-06-04 16:43
> **Edited:** Uncheck this setting solved the issue for me!!! ![image](https://user-images.githubusercontent.com/88484339/241705894-42e8d748-3d15-4285-8b12-8fc8d51e30e2.png)

Vanilla OS 22.10 - This fixes the issue!

**Comment by ttoommxx** [comment] 2023-06-13 22:08
The option was removed and the problem is back. Any solution?

**Comment by fabianmuehlberger** [comment] 2023-06-14 16:10
+1

**Comment by adlermo** [comment] 2023-06-15 21:08
In Help -> About

```
**Visual Studio Code**
Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.10.0-23-amd64
```

Option _Use Sandbox_ mentioned above is no longer available

**Comment by tfrum** [comment] 2023-06-15 23:10
> The option _Use Sandbox_ mentioned above is no longer available

Confirming this is an issue for me, as well:

```
Version: 1.79.1
Release: 23164
Commit: 5d4b595142dd2d0a0001531e9c48b36fc795cef2
Date: 2023-06-13T18:23:51.444Z
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.5-200.fc38.x86_64
```

**Comment by Aqua1ung** [comment] 2023-06-16 19:21
> The option _Use Sandbox_ mentioned above is no longer available

Ditto.
```
Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.8-1321.native
```

**Comment by Viktror-INC** [comment] 2023-06-18 11:48
The same, dont have Use Sandbox inner

Version: 1.79.0
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:28:44.251Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.8-200.fc38.x86_64

**Comment by PauloCabral-hub** [comment] 2023-06-18 21:30
> I installed it form official vs code website and the issue is gone

Did the same here and solved the problem.

**Comment by ttoommxx** [comment] 2023-06-18 22:50
Yeah but I'd like to know if this problem can be solved on the flatpak
version, given the success of immutable distros these days they should get
it fixed at some point!

**Comment by bantryblues** [comment] 2023-06-18 22:58
Didn’t they remove the setting that was a ?

**Comment by AkakiAki** [comment] 2023-06-21 13:18
I had the same issue with flatpak and managed to fix it, this link might help solve it:
https://github.com/flathub/com.visualstudio.code#readme

**Comment by ttoommxx** [comment] 2023-06-21 13:53
Oh ok ok, I guess this solves it! @jorchube can you close the thread referring to the comment above?

**Comment by Aqua1ung** [comment] 2023-06-21 14:43
> I had the same issue with flatpak and managed to fix it, this link might help solve it: https://github.com/flathub/com.visualstudio.code#readme

https://github.com/flathub/com.visualstudio.code/issues/407

**Comment by alexojegu** [comment] 2023-06-21 19:24
> Oh ok ok, I guess this solves it! @jorchube can you close the thread referring to the comment above?

I don't want "use host shell in the integrated terminal".I don't have installed on my host Git, NodeJS, npm...

**Comment by ttoommxx** [comment] 2023-06-22 08:10
> > Oh ok ok, I guess this solves it! @jorchube can you close the thread referring to the comment above?
> 
> I don't want "use host shell in the integrated terminal". I don't have installed on my host Git, NodeJS, npm...

you literally ONLY have to add those few lines, you don't have to install anything... did you give it a try?

**Comment by radurentea** [comment] 2023-06-22 11:17
I had same problem on Fedora cause I've installed VSCode via "Software App". I've reinstalled it following VSCode documentation and I have no more issues with the terminal. https://code.visualstudio.com/docs/setup/linux

**Comment by Leonw43** [comment] 2023-06-23 19:11
> > > Oh ok ok, I guess this solves it! @jorchube can you close the thread referring to the comment above?
> > 
> > 
> > I don't want "use host shell in the integrated terminal". I don't have installed on my host Git, NodeJS, npm...
> 
> you literally ONLY have to add those few lines, you don't have to install anything... did you give it a try?

I've tried this and still having the same issue - PopOS 22.04

**Comment by tfrum** [comment] 2023-06-23 21:27
> > > Oh ok ok, I guess this solves it! @jorchube can you close the thread referring to the comment above?
> > 
> > I don't want "use host shell in the integrated terminal". I don't have installed on my host Git, NodeJS, npm...
> 
> you literally ONLY have to add those few lines, you don't have to install anything... did you give it a try?

My friend, closing the thread for a workaround instead of a fix isn't preferable. Test your fix to see if there are any externalities, wait until other people have tried it, but most of all we need to figure out why this is an issue to begin with and *patch* it.

**Comment by fjbaldon** [comment] 2023-06-24 01:03
> > > Oh ok ok, I guess this solves it! @jorchube can you close the thread referring to the comment above?
> > 
> > 
> > I don't want "use host shell in the integrated terminal". I don't have installed on my host Git, NodeJS, npm...
> 
> you literally ONLY have to add those few lines, you don't have to install anything... did you give it a try?

Isn't that just using the host shell?

**Comment by h4kon** [comment] 2023-06-24 17:35
Hello, I'm having the same problem here, Fedora Kinoite 38. Does it still persist?

**Comment by ttoommxx** [comment] 2023-06-25 09:50
Guys, be sure to include those lines without the curly brackets at the beginning

**Comment by h4kon** [comment] 2023-06-25 21:48
> Guys, be sure to include those lines without the curly brackets at the beginning

It partially works, for me it returns this bash error: cannot set terminal process group (-1): Inappropriate ioctl for device.

**Comment by cheese** [comment] 2023-06-26 10:11
My quick workaround:

```json
{
    "terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "env",
            "icon": "terminal-bash",
            "args": [
                "--unset", "LD_PRELOAD",
                "--unset", "SANDBOX_LD_PRELOAD",
                "bash", "--init-file",
                "/app/extra/vscode/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
            ],
        },
    }
}
```

**Comment by olekzonder** [comment] 2023-06-28 22:16
> My quick workaround:
> 
> ```json
> {
>     "terminal.integrated.defaultProfile.linux": "bash",
>     "terminal.integrated.profiles.linux": {
>         "bash": {
>             "path": "env",
>             "icon": "terminal-bash",
>             "args": [
>                 "--unset", "LD_PRELOAD",
>                 "--unset", "SANDBOX_LD_PRELOAD",
>                 "bash", "--init-file",
>                 "/app/extra/vscode/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
>             ],
>         },
>     }
> }
> ```

That's a great solution! Worked for me flawlessly! Thanks, man!

**Comment by Aqua1ung** [comment] 2023-06-28 22:42
> My quick workaround:
> 
> ```json
> {
>     "terminal.integrated.defaultProfile.linux": "bash",
>     "terminal.integrated.profiles.linux": {
>         "bash": {
>             "path": "env",
>             "icon": "terminal-bash",
>             "args": [
>                 "--unset", "LD_PRELOAD",
>                 "--unset", "SANDBOX_LD_PRELOAD",
>                 "bash", "--init-file",
>                 "/app/extra/vscode/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh"
>             ],
>         },
>     }
> }
> ```

What _precisely_ is this a workaround for? Does it prevent these pesky `preload-host-spawn-strategy] Warning: waitpid override ignores groups` messages? And how do you combine this solution with the ["use the host shell in the integrated terminal" trick](https://github.com/flathub/com.visualstudio.code/issues/407)?

**Comment by Bereriche** [comment] 2023-07-03 18:23
popOs here.. removed the flatpack version and installed the deb version .. that did it for me.. thanks

**Comment by tfrum** [comment] 2023-07-03 18:57
> popOs here.. removed the flatpack version and installed the deb version .. that did it for me.. thanks

 In the initial post it was noted that this is a flatpak-only issue.

**Comment by eduncan911** [comment] 2023-07-04 00:08
> I think I found a simpler workaround for Flatpak users.
> 
> The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     },
> ```
> 
> No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.

This worked for me as well.

Pop_OS 22.04 LTS, Regolith Desktop

I use VSCodium and not VSCode, still worked!

```
    "terminal.integrated.env.linux": {
        "LD_PRELOAD": null,
    }
```

**Comment by ttoommxx** [comment] 2023-07-04 09:07
Anyhow, the official fix on the github repo works for everyone and the
discussion has shifted to a different issue. Can we not just close this and
you guys open a new thread for the LD_PRELOAD thingy?

**Comment by AlexAtkinson** [comment] 2023-07-05 19:24
I'm on Pop!_OS and have this issue with the flatpak from the Pop!_Shop application store.
To resolve, as mentioned above, I removed the flatpak, picked the deb installer from the dropdown menu (still in the Pop!_Shop), and installed it this way.

**Comment by Aqua1ung** [comment] 2023-07-05 20:16
> I'm on Pop!_OS and have this issue with the flatpak from the Pop!_Shop application store. To resolve, as mentioned above, I removed the flatpak, picked the deb installer from the dropdown menu (still in the Pop!_Shop), and installed it this way.

We don't all have the luxury of being able to install the _native_ application, hence we are resorting to the Flatpak version. Which is why we would like to see the Flatpak package work properly.

**Comment by tfrum** [comment] 2023-07-05 21:35
> I'm on Pop!_OS and have this issue with the flatpak from the Pop!_Shop application store.
> To resolve, as mentioned above, I removed the flatpak, picked the deb installer from the dropdown menu (still in the Pop!_Shop), and installed it this way.

Please when you respond to a GitHub problem report read the initial post. This is noted as a flatpak issue. The solution for the problem is not just not using flatpak as far as a GitHub problem for the flatpak version goes.

**Comment by billy44dev** [comment] 2023-07-05 23:00
> > I think I found a simpler workaround for Flatpak users.
> > The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> > ```
> >     "terminal.integrated.env.linux": {
> >         "LD_PRELOAD": null,
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.
> 
> This worked for me as well.
> 
> Pop_OS 22.04 LTS, Regolith Desktop
> 
> I use VSCodium and not VSCode, still worked!
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     }
> ```

Worked for me as well, thanks!! using pop_os 22.04 LTS.

**Comment by ian-henderson** [comment] 2023-07-08 19:11
> I think I found a simpler workaround for Flatpak users.
> 
> The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     },
> ```
> 
> No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.

This worked for me on Debian 12 with flatpak VSCodium - thanks!

**Comment by bantryblues** [comment] 2023-07-09 04:35
Can this be added by the people who create the vscode flatpak so it just works without having to know to do this?

**Comment by Bala-0-1** [comment] 2023-07-21 15:11
> I think I found a simpler workaround for Flatpak users.
> 
> The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     },
> ```
> 
> No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.

**Comment by Bala-0-1** [comment] 2023-07-21 15:11
Thanks : )

**Comment by cassiofb-dev** [comment] 2023-07-29 22:17
> I think I found a simpler workaround for Flatpak users.
> 
> The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     },
> ```
> 
> No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.

Also worked for me on Alpine 3.18, thanks!

![image](https://github.com/flathub/com.visualstudio.code/assets/61878987/006ff822-20ee-4668-8682-7a18a9210329)

**Comment by siriokun** [comment] 2023-08-02 15:09
Installing [Starship](https://starship.rs/) also solve this issue.

**Comment by didymus81** [comment] 2023-08-05 14:06
> I think I found a simpler workaround for Flatpak users.
> 
> The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     },
> ```
> 
> No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.

Yeah, it works!

![imagen](https://github.com/flathub/com.visualstudio.code/assets/54082322/0076fd44-c41e-4de4-b921-0e84160a7e6b)

My settings.json

![imagen](https://github.com/flathub/com.visualstudio.code/assets/54082322/1efd5380-64d3-4ffd-89cb-8a2e486e237f)

Thanks a lot!

**Comment by islamux** [comment] 2023-08-14 14:40
> > I think I found a simpler workaround for Flatpak users.
> > The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> > ```
> >     "terminal.integrated.env.linux": {
> >         "LD_PRELOAD": null,
> >     },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.
> 
> This worked for me as well.
> 
> Pop_OS 22.04 LTS, Regolith Desktop
> 
> I use VSCodium and not VSCode, still worked!
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     }
> ```

Fedora 38 
Flatpak 

Thanks  ^_^
Works for me like a charm !

**Comment by alexojegu** [comment] 2023-08-14 18:15
> so why dont they fix it in the flatpak?

@bantryblues, if you read what you quote you will see that the bug is in [zypak](https://github.com/refi64/zypak) and the [fix](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d) was commited on Jul 1 but the last [release](https://github.com/refi64/zypak/releases) was on Apr 18, 2022 so maybe the flatpak package maintainers are waiting for a new release of this dependency...

**Comment by islamux** [comment] 2023-08-16 04:15
> > > I think I found a simpler workaround for Flatpak users.
> > > The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> > > ```
> > >     "terminal.integrated.env.linux": {
> > >         "LD_PRELOAD": null,
> > >     },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.
> > 
> > 
> > This worked for me as well.
> > Pop_OS 22.04 LTS, Regolith Desktop
> > I use VSCodium and not VSCode, still worked!
> > ```
> >     "terminal.integrated.env.linux": {
> >         "LD_PRELOAD": null,
> >     }
> > ```
> 
> Fedora 38 Flatpak
> 
> Thanks ^_^ Works for me like a charm !

I reinstaledl it based on recommendation in its site , to avoid the problem in flatpak.

**Comment by Sircule14** [comment] 2023-09-01 02:44
> I installed it form official vs code website and the issue is gone

I do it and it works.
Thank you so much man

**Comment by PythonCoderUnicorn** [comment] 2023-09-02 02:27
I tried all of the suggestions. I uninstalled, reinstalled from flatpak and Pop! Shop. I tried changing the README settings but did not work. when i tried to paste the snippet i could not save the file.

I just uninstalled it, as no one shared where to locate this file other than the  initial app load that shows README. I just wanted a code editor to work.

**Comment by binuvijayan893** [comment] 2023-09-13 12:36
Install from [officel ](https://code.visualstudio.com/Download)

**Comment by GregLawson** [comment] 2023-09-15 14:15
> I tried all of the suggestions. I uninstalled, reinstalled from flatpak and Pop! Shop. I tried changing the README settings but did not work. when i tried to paste the snippet i could not save the file.

>I just uninstalled it, as no one shared where to locate this file other than the initial app load that shows README. I just wanted a code editor to work.

For those unfamiliar with editing VSCode settings.json files:

1. In VsCode or VsCodium pick the File menu > Preferences > Settings (or control-, as a shortcut)
you should be presented with a settings Search settings bar,
1. paste into the search "terminal.integrated.env.linux" without the double quotes,
1. click on the "Edit in settings.json"
1. paste ""LD_PRELOAD": null," (again without the quotes)
1. Review the JSON for cut /paste errors and you're done.

**Comment by vaibzzz123** [comment] 2023-09-16 03:36
Did anyone get this working on Fedora 38? Still having the issues after doing the LD_PRELOAD override in the settings.json file

**Comment by GregLawson** [comment] 2023-09-16 14:55
I got this working on Fedora 38 Kinoite with both the VsCode and VsCodium flatpaks.

**Comment by bensalo** [comment] 2023-09-20 12:11
+1 flatpak vscode on fedora 38 workstation

**Comment by eclipseo** [comment] 2023-09-24 08:25
I don't have the issue, do you guys have

```
	// Object with environment variables that will be added to the VS Code process to be used by the terminal on Linux. Set to `null` to delete the environment variable.
	"terminal.integrated.env.linux": {},
```
in your `defaultsettings.json`?

**Comment by KrauzerPH94** [comment] 2023-09-26 16:12
> > **Edited:** Uncheck this setting solved the issue for me!!! ![image](https://user-images.githubusercontent.com/88484339/241705894-42e8d748-3d15-4285-8b12-8fc8d51e30e2.png)
> 
> This is the answer. The flatpak should see if it's possible to override this setting, as it comes enabled by default. Principle of most astonishment, I guess...

I can't find this setting on my Flatpak VS Code

**Comment by rtweaf** [comment] 2023-10-06 15:58
Same issue on PopOS - flatpak.

**Comment by ehmad11** [comment] 2023-10-07 18:50
> > I tried all of the suggestions. I uninstalled, reinstalled from flatpak and Pop! Shop. I tried changing the README settings but did not work. when i tried to paste the snippet i could not save the file.
> 
> > I just uninstalled it, as no one shared where to locate this file other than the initial app load that shows README. I just wanted a code editor to work.
> 
> For those unfamiliar with editing VSCode settings.json files (I, too, was a little fuzzy while reading these comments):
> 
> 1. In VsCode or VsCodium pick the File menu > Preferences > Settings (or control-, as a shortcut)
>    you should be presented with a Search settings bar,
> 2. paste into the search "terminal.integrated.env.linux" without the double quotes,
> 3. click on the "Edit in settings.json",
> 4. paste ""LD_PRELOAD": null," (again without the quotes) into the bracketed JSON expression,
> 5. Review the JSON for cut /paste errors. You should see:
> 
> > "terminal.integrated.env.linux": {
> > "LD_PRELOAD": null,
> > }
> 
> 6. Save the settings.json file,
> 7. Restart your VsCode terminal for the new settings.json to take effect.

Thank you @GregLawson, it worked for me on Fedora 38.

**Comment by SeLub** [comment] 2023-10-24 11:46
Same issue on PopOS - flatpak. Solved by adding to the settings.json:

"terminal.integrated.env.linux": {
        "LD_PRELOAD": null,
    },

**Comment by brieucdlf** [comment] 2023-10-27 16:53
Thanks @iihmsunn for the tips :) Same issue on PopOS.

**Comment by vendkura** [comment] 2023-11-12 07:48
> I installed it form official vs code website and the issue is gone

It works for me too

**Comment by isikhi** [comment] 2023-11-16 09:39
Same issue  LD_PRELOAD worked for me.
```
    "terminal.integrated.env.linux": {
        "LD_PRELOAD": null,
    }
```

**Comment by shubhsharma19** [comment] 2023-12-05 19:06
![Screenshot from 2023-12-06 00-36-03](https://github.com/flathub/com.visualstudio.code/assets/69891912/ff82ed43-fc6b-49af-b5f6-28d326b60574)
Happening with me as well I will try to install it using official website now.

**Comment by iamWing** [comment] 2023-12-16 16:17
> Same issue LD_PRELOAD worked for me.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     }
> ```

This fixed the issue for me on Steam Deck using the flatpak version. Thanks.

**Comment by gitsoft** [comment] 2024-01-02 19:20
Solution on POP OS 22.04

![vscode_info](https://github.com/flathub/com.visualstudio.code/assets/1828815/fa8a4933-87d0-4e74-aba6-51875e77c74f)

1. Open Pop!_Shop
2. Find Visual Studio Code
3. Uninstall
4. Go to [https://code.visualstudio.com/download](https://code.visualstudio.com/download)
5. Download latest .deb package for your CPU architecture
6. cd to folder where you keep downloaded files 
7. `sudo dpkg -i code_1.85.1-1702462158_amd64.deb`

please note: _the filename will most likely be different for you_.

**Comment by kalwhyte** [comment] 2024-01-07 09:06
> I installed it form official vs code website and the issue is gone

This was a simple and direct fix

Thank You

**Comment by AndreiSva** [comment] 2024-01-08 20:32
installing it from the vscode website is not a fix. Is it possible to fix this in the flatpak?

**Comment by AndreiSva** [comment] 2024-01-08 21:23
> I think I found a simpler workaround for Flatpak users.
> 
> The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     },
> ```
> 
> No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.

would it be possible to build this fix into the flatpak?

**Comment by Mateusinbessa** [comment] 2024-01-17 01:04
> I think I found a simpler workaround for Flatpak users.
> 
> The issue seems to be the LD_PRELOAD environmental variable based on [a fix that was recently committed to the affected component](https://github.com/refi64/zypak/commit/b4607cc258f5ac48a236580661c8c633ddb89b5d). Since VS Code has a setting for changing environmental variables for the integrated terminals, I just needed to add the following entry to my settings.json file to unset that variable and stop the errors.
> 
> ```
>     "terminal.integrated.env.linux": {
>         "LD_PRELOAD": null,
>     },
> ```
> 
> No other environmental variables beyond the one entered in the setting appear to be affected, so things like $PATH or SDK-specific environmental variables should remain unchanged.

Ubuntu 22.04
Thx! It worked for me!

**Comment by christopolise** [comment] 2024-02-07 16:54
> a workaround for vscode that seems to be working for me is to add these to settings.json
> 
> ```
> "terminal.integrated.defaultProfile.linux": "bash",
> "terminal.integrated.profiles.linux": {
>     "bash": {
>         "path": "/usr/bin/flatpak-spawn",
>         "args": [
>             "--env=TERM=xterm-256color",
>             "bash",
>             //next two lines are only required if you use external sdks, edit to use yours
>             "-c",
>             "export PATH=$PATH:/usr/lib/sdk/dotnet7/bin:/usr/lib/sdk/node18/bin; bash"
>         ]
>     }
> }
> ```

I was having an issue just dropping in `zsh` as a replacement and found out that I needed to add the `--host` option to the `args` list to make it work. Hopes this saves someone some time:

```
"terminal.integrated.defaultProfile.linux": "zsh",
"terminal.integrated.profiles.linux": {
        "zsh": {
            "path": "/usr/bin/flatpak-spawn",
            "args": [
                "--host",
                "--env=TERM=xterm-256color",
                "zsh",
                //next two lines are only required if you use external sdks, edit to use yours
                // "-c",
                // "export PATH=$PATH:/usr/lib/sdk/dotnet7/bin:/usr/lib/sdk/node18/bin; bash"
            ]
        }
    }
```

**Comment by rakibce30** [comment] 2024-02-24 04:17
> Same issue on PopOS - flatpak. Solved by adding to the settings.json:
> 
> "terminal.integrated.env.linux": { "LD_PRELOAD": null, },

It's working....

**Closed** 2024-02-25 18:27 UTC
